
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('plants').del()
    .then(function () {
      // Inserts seed entries
      return knex('plants').insert([
        {
          name: 'Anubias barteri var. nana',
          growth_rate: 'Slow',
          light_requirement: 'Low',
          co2_need: 'Low',
          structure: 'Rhizome',
          size: 'Midground',
          isFloating: true,
          price: '5.00',
          photo_url: 'https://upload.wikimedia.org/wikipedia/commons/b/b7/Anubias.jpg',
          stock: 20
        },
        {
          name: 'Rotala rotundifolia (Dwarf Rotala)',
          growth_rate: 'Fast',
          light_requirement: 'Medium',
          co2_need: 'Low',
          structure: 'Stem',
          size: 'Midground',
          isFloating: false,
          price: '5.00',
          photo_url: 'https://cdn.shopify.com/s/files/1/0819/6279/products/rotala_green_3_eaad16ba-8eb4-4c2c-8045-ba06a838647f_1024x1024.jpg?v=1520919063',
          stock: 10
        },
        {
          name: 'Taxiphyllum barbieri (Java Moss)',
          growth_rate: 'Medium',
          light_requirement: 'Low',
          co2_need: 'Low',
          structure: 'Moss',
          size: 'Foreground',
          isFloating: true,
          price: '5.00',
          photo_url: 'https://upload.wikimedia.org/wikipedia/commons/a/a5/Javamoos.jpg',
          stock: 30
        },
        {
          name: 'Hydrocotyle leucocephala (Brazillian Pennywort)',
          growth_rate: 'Fast',
          light_requirement: 'Medium',
          co2_need: 'Low',
          structure: 'Free-Floating',
          size: 'Surface',
          isFloating: true,
          price: '5.00',
          photo_url: 'https://m.media-amazon.com/images/S/aplus-seller-content-images-us-east-1/ATVPDKIKX0DER/A2YV2RR0EWEZ5/B00M3COKZO/MOskZonKQ2mu._UX970_TTW__.jpg',
          stock: 30
        },
        {
          name: 'Hygrophila difformis (Water Wisteria)',
          growth_rate: 'Fast',
          light_requirement: 'Medium',
          co2_need: 'Low',
          structure: 'Stem',
          size: 'Background',
          isFloating: false,
          price: '5.00',
          photo_url: 'https://upload.wikimedia.org/wikipedia/commons/b/ba/Hygrophila_difformis.jpg',
          stock: 30
        },
        {
          name: 'Bacopa monnieri (Moneywort)',
          growth_rate: 'Medium',
          light_requirement: 'Medium',
          co2_need: 'Low',
          structure: 'Stem',
          size: 'Background',
          isFloating: false,
          price: '5.00',
          photo_url: 'https://upload.wikimedia.org/wikipedia/commons/7/75/Bacopa_monnieri_BotGardBln07122011A.jpg',
          stock: 30
        },
        {
          name: 'Lemma spp. (Duckweed)',
          growth_rate: 'Fast',
          light_requirement: 'Low',
          co2_need: 'Low',
          structure: 'Free-Floating',
          size: 'Surface',
          isFloating: true,
          price: '5.00',
          photo_url: 'https://upload.wikimedia.org/wikipedia/commons/f/f8/LentejasDeAgua.jpg',
          stock: 30
        },
        {
          name: 'Sagittaria sublata (Dwarf Sagittaria)',
          growth_rate: 'Fast',
          light_requirement: 'Low',
          co2_need: 'Low',
          structure: 'Rosette',
          size: 'Foreground',
          isFloating: false,
          price: '5.00',
          photo_url: 'https://shop.plantedaquariumscentral.com/assets/images/dw%20sag1.jpg',
          stock: 30
        },
        {
          name: 'Nymphaea lotus',
          growth_rate: 'Fast',
          light_requirement: 'Medium',
          co2_need: 'Low',
          structure: 'Rosette',
          size: 'Background',
          isFloating: false,
          price: '5.00',
          photo_url: 'https://upload.wikimedia.org/wikipedia/commons/9/97/Nymphaea_lotus.JPG',
          stock: 30
        },
        {
          name: 'Fissidens fontanus (Phoenix Moss)',
          growth_rate: 'Medium',
          light_requirement: 'Low',
          co2_need: 'Low',
          structure: 'Moss',
          size: 'Midground',
          isFloating: true,
          price: '5.00',
          photo_url: 'https://aquascapers.files.wordpress.com/2012/07/fissidens_fontanus.jpg',
          stock: 30
        },
        {
          name: 'Echinodorus grisebachii "Amazonicus" (Amazon Sword)',
          growth_rate: 'Fast',
          light_requirement: 'Medium',
          co2_need: 'low',
          structure: 'Rosette',
          size: 'Background',
          isFloating: false,
          price: '5.00',
          photo_url: 'https://www.flowgrow.de/db/images/aquaticplants/detail/echinodorus-grisebachii-amazonicus-53cdfe79b9451.jpg',
          stock: 30
        },
        {
          name: 'Hemianthus callitrichoides "Cuba" (Dwarf Baby Tears)',
          growth_rate: 'Medium',
          light_requirement: 'High',
          co2_need: 'Medium',
          structure: 'Stem',
          size: 'Foreground',
          isFloating: false,
          price: '5.00',
          photo_url: 'https://i0.wp.com/aquaticmag.com/wp-content/uploads/2015/11/Heminathus-Callitrichoides-HC-Dwarf-Baby-Tears-Information-and-Caresheet-Dwarf-Baby-Tears-HC-for-sale-AquaticMag-8.jpg',
          stock: 30
        },
        {
          name: 'Staurogyne repens',
          growth_rate: 'Medium',
          light_requirement: 'Medium',
          co2_need: 'Medium',
          structure: 'Stem',
          size: 'Foreground',
          isFloating: false,
          price: '5.00',
          photo_url: 'https://aquaticmag.com/wp-content/uploads/2014/07/Staurogyne-Repens-049-Aquatic-plant-for-sale-and-where-to-buy-Aquaticmag.jpg',
          stock: 0
        },
        {
          name: 'Heteranthera zosterifolia (Stargrass)',
          growth_rate: 'Fast',
          light_requirement: 'Medium',
          co2_need: 'Low',
          structure: 'Stem',
          size: 'Background',
          isFloating: false,
          price: '10.00',
          photo_url: 'https://www.liquidcreations.co/wp-content/uploads/2018/02/IMG_20160604_131828.jpg',
          stock: 20
        },
        {
          name: 'Ludwigia repens',
          growth_rate: 'Fast',
          light_requirement: 'Medium',
          co2_need: 'Low',
          structure: 'Stem',
          size: 'Background',
          isFloating: false,
          price: '7.00',
          photo_url: 'https://shop.plantedaquariumscentral.com/assets/images/ludwigia20repens20broad20leaf.jpg',
          stock: 30
        },
        {
          name: 'Ammannia gracilis',
          growth_rate: 'Fast',
          light_requirement: 'Medium',
          co2_need: 'Medium',
          structure: 'Stem',
          size: 'Background',
          isFloating: false,
          price: '8.00',
          photo_url: 'https://aquaticworldinfo.com/wp-content/uploads/2017/09/Ammannia-Gracilis.jpg',
          stock: 10
        },
        {
          name: 'Echinodorus palifolius',
          growth_rate: 'Fast',
          light_requirement: 'Medium',
          co2_need: 'Low',
          structure: 'Rosette',
          size: 'Background',
          isFloating: false,
          price: '5.00',
          photo_url: 'https://www.aqvium.ru/images/plant/rosette-plants/Echinodorus/68-3.Echinodorus-ozelot.jpg',
          stock: 30
        },
        {
          name: 'Aponogeton boivinianus',
          growth_rate: 'Fast',
          light_requirement: 'Medium',
          co2_need: 'Low',
          structure: 'Rosette',
          size: 'Background',
          isFloating: false,
          price: '7.00',
          photo_url: 'https://www.aquasabi.de/vcdn/images/item/zoom/ZViG216Uxg/aponogeton-boivinianus-2.jpg',
          stock: 20
        },
        {
          name: 'Riccardia spp.',
          growth_rate: 'Slow',
          light_requirement: 'Medium',
          co2_need: 'Low',
          structure: 'Moss',
          size: 'Foreground',
          isFloating: true,
          price: '5.00',
          photo_url: 'https://www.flowgrow.de/db/images/wasserpflanzen/detail/riccardia-spp-514a32a858b60.jpg',
          stock: 10
        },
        {
          name: 'Cryptocoryne x willisii "lucens"',
          growth_rate: 'Slow',
          light_requirement: 'Low',
          co2_need: 'Low',
          structure: 'Rosette',
          size: 'Foreground',
          isFloating: false,
          price: '4.00',
          photo_url: 'https://www.plantedtank.net/forums/images/plants/112_Cryptocoryne_x_willisii_Cryptocoryne_x_willisii_lucens.e.jpg',
          stock: 50
        },
        {
          name: 'Cryptocoryne undulata',
          growth_rate: 'Medium',
          light_requirement: 'Low',
          co2_need: 'Low',
          structure: 'Rosette',
          size: 'Foreground',
          isFloating: false,
          price: '5.00',
          photo_url: 'https://www.aquaticplantcentral.com/forumapc/plantfinder/images/Araceae/Cryptocoryneundulata.jpg',
          stock: 50
        },
        {
          name: 'Hygrophila pinnatifida',
          growth_rate: 'Medium',
          light_requirement: 'High',
          co2_need: 'Medium',
          structure: 'Rosette',
          size: 'Background',
          isFloating: false,
          price: '10.00',
          photo_url: 'https://shop.plantedaquariumscentral.com/assets/images/hygropinn1.jpg',
          stock: 10
        },
        {
          name: 'Cabomba caroliniana var. caroliniana',
          growth_rate: 'Fast',
          light_requirement: 'Medium',
          co2_need: 'Medium',
          structure: 'Stem',
          size: 'Background',
          isFloating: false,
          price: '10.00',
          photo_url: 'http://www.pianetacquario.it/images/stories/FOTO/cabomba%20caroliniana.jpg',
          stock: 20
        },
        {
          name: 'Vesicularia montagnei (Christmas Moss)',
          growth_rate: 'Slow',
          light_requirement: 'Low',
          co2_need: 'Low',
          structure: 'Moss',
          size: 'Foreground',
          isFloating: true,
          price: '5.00',
          photo_url: 'https://www.azgardens.com/wp-content/uploads/2017/06/Christmas-Moss-Taxiphyllum-alternans.jpg',
          stock: 20
        },
        {
          name: 'Monosolenium tenerum (Liverwort)',
          growth_rate: 'Medium',
          light_requirement: 'Medium',
          co2_need: 'Low',
          structure: 'Moss',
          size: 'Foreground',
          isFloating: true,
          price: '7.00',
          photo_url: 'https://acimg.auctivacommerce.com/imgdata/0/2/9/3/2/4/webimg/4556923.jpg',
          stock: 10
        },
      ]);
    });
};
